spring.application.name=EmailVerification

spring.datasource.url=jdbc:mysql://localhost:3306/ums
spring.datasource.username=root
spring.datasource.password=Sinojk@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sellasinoj@gmail.com
spring.mail.password=kmdxjwokgcqbcdra

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true